# Atributos de gusanos:
puntos_de_vida: 100
cantidad_de_vidas: 1

# Atributos de armas:

# Frags
cantidad_frags: 6
danio_frags: 10
radio_frags: 2

# Bazooka
dmg_bazooka: 50
radio_bazooka: 2

# Mortero
ammo_mortero: 10
dmg_mortero: 50
radio_mortero: 2

# Granada Verde
dmg_granada_verde: 30
radio_granada_verde: 2

# Granada Roja
ammo_granada_roja: 10
dmg_granada_roja: 30
radio_granada_roja: 2

# Banana
ammo_banana: 5
dmg_banana: 70
radio_banana: 4

# Granada Santa
ammo_santa: 2
dmg_santa: 110
radio_santa: 8

# Dinamita
ammo_dinamita: 5
dmg_dinamita: 50
radio_dinamita: 4

# Bate
dmg_bate: 10

# Air Strike
num_misiles: 6
ammo_misiles: 2
dmg_misil: 40
radio_misil: 2

# Provisiones
provision_healing: 40
provision_explosion_dmg: 30
