# Atributos de gusanos:
puntos_de_vida: 100
cantidad_de_vidas: 1

# Atributos de armas:
# Bazooka
dmg_bazooka: 50
radio_bazooka: 2

# Mortero
ammo_mortero: 10
dmg_mortero: 50
radio_mortero: 2
dmg_mortero_frag: 10
radio_mortero_frag: 2
mortero_frags: 6

# Granada Verde
dmg_granada_verde: 30
radio_granada_verde: 2

# Granada Roja
ammo_granada_roja: 10
dmg_granada_roja: 30
radio_granada_roja: 2
dmg_granada_roja_frag: 10
radio_granada_roja_frag: 2
granada_roja_frags: 6

# Banana
ammo_banana: 5
dmg_banana: 70
radio_banana: 4

# Granada Santa
ammo_santa: 2
dmg_santa: 110
radio_santa: 8

# Dinamita
ammo_dinamita: 5
dmg_dinamita: 50
radio_dinamita: 4

# Bate
dmg_bate: 10

# Air Strike
num_misiles: 6
ammo_misiles: 2
dmg_misil: 40
radio_misil: 2
