#ifndef CHEATS_H
#define CHEATS_H


enum Cheats{
    VIDA_INFINITA = 0,
    MUNICION_INFINITA = 1,
    SUPER_SALTO = 2,
    SUPER_VELOCIDAD = 3,
    SETEAR_VIDA_A_1 = 4,
    MATAR_TODOS_LOS_GUSANOS_ENEMIGOS = 5
};


#endif