#ifndef SOUND_TYPES_H
#define SOUND_TYPES_H

enum SoundTypes {
    AIR_STRIKE,
    BANANA_BOUNCE,
    GRENADE_BOUNCE,
    BAT_EQUIP,
    BAT_ATTACK,
    HURT_WORM,
    EXPLOSION,
    FUSE,
    SPLASH,
    TELEPORT,
    GROUND_CONTACT,
    WORM_DEATH_CRY,
    WORM_HURT_SHOUT,
    WORM_GRENADE_SHOUT,
    WORM_BAZOOKA_SHOUT,
    WIN
};

#endif
